name: ContractBoard
version: '1.0.0'
main: com.contractboard.ContractBoardPlugin
api-version: '1.20'
authors: [ ContractBoard ]
description: Contract board system for factions.
commands:
  contracts:
    description: Open contracts GUI
    aliases: [ cb ]
    permission: contractboard.use
  contractsadmin:
    description: ContractBoard admin commands
    aliases: [ cba ]
    permission: contractboard.admin
permissions:
  contractboard.use:
    description: Use contracts GUI
    default: true
  contractboard.admin:
    description: Admin commands
    default: op
